#!/usr/bin/env bash

if [ -z $1 ]; then
	read -p "Note name: " name
else
	name=$1
fi
filename="${name}.md"

if [ ! -d ~/notes ]; then
	mkdir ~/notes
fi

if [ -a "~/notes/$filename" ]; then
	echo "file already exists" >&2
	exit 1
fi

cd ~/notes

echo "# $name" > $filename

$EDITOR "${name}.md"



